# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: grpc/chirpstack_api/device.proto
# Protobuf Python Version: 6.31.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    0,
    '',
    'grpc/chirpstack_api/device.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n grpc/chirpstack_api/device.proto\x12\x0e\x63hirpstack.api\"#\n\x10GetDeviceRequest\x12\x0f\n\x07\x64\x65v_eui\x18\x01 \x01(\t\"z\n\x11GetDeviceResponse\x12\x0f\n\x07\x64\x65v_eui\x18\x01 \x01(\t\x12\x0c\n\x04name\x18\x02 \x01(\t\x12\x13\n\x0b\x64\x65scription\x18\x03 \x01(\t\x12\x16\n\x0e\x61pplication_id\x18\x04 \x01(\t\x12\x19\n\x11\x64\x65vice_profile_id\x18\x05 \x01(\t\"|\n\x13\x43reateDeviceRequest\x12\x0f\n\x07\x64\x65v_eui\x18\x01 \x01(\t\x12\x0c\n\x04name\x18\x02 \x01(\t\x12\x13\n\x0b\x64\x65scription\x18\x03 \x01(\t\x12\x16\n\x0e\x61pplication_id\x18\x04 \x01(\t\x12\x19\n\x11\x64\x65vice_profile_id\x18\x05 \x01(\t\"\x16\n\x14\x43reateDeviceResponse\"&\n\x13\x44\x65leteDeviceRequest\x12\x0f\n\x07\x64\x65v_eui\x18\x01 \x01(\t\"\x16\n\x14\x44\x65leteDeviceResponse2\x85\x02\n\rDeviceService\x12J\n\x03Get\x12 .chirpstack.api.GetDeviceRequest\x1a!.chirpstack.api.GetDeviceResponse\x12S\n\x06\x43reate\x12#.chirpstack.api.CreateDeviceRequest\x1a$.chirpstack.api.CreateDeviceResponse\x12S\n\x06\x44\x65lete\x12#.chirpstack.api.DeleteDeviceRequest\x1a$.chirpstack.api.DeleteDeviceResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'grpc.chirpstack_api.device_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_GETDEVICEREQUEST']._serialized_start=52
  _globals['_GETDEVICEREQUEST']._serialized_end=87
  _globals['_GETDEVICERESPONSE']._serialized_start=89
  _globals['_GETDEVICERESPONSE']._serialized_end=211
  _globals['_CREATEDEVICEREQUEST']._serialized_start=213
  _globals['_CREATEDEVICEREQUEST']._serialized_end=337
  _globals['_CREATEDEVICERESPONSE']._serialized_start=339
  _globals['_CREATEDEVICERESPONSE']._serialized_end=361
  _globals['_DELETEDEVICEREQUEST']._serialized_start=363
  _globals['_DELETEDEVICEREQUEST']._serialized_end=401
  _globals['_DELETEDEVICERESPONSE']._serialized_start=403
  _globals['_DELETEDEVICERESPONSE']._serialized_end=425
  _globals['_DEVICESERVICE']._serialized_start=428
  _globals['_DEVICESERVICE']._serialized_end=689
# @@protoc_insertion_point(module_scope)
