# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: device_profile/device_profile.proto
# Protobuf Python Version: 6.31.1

from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder


_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'device_profile/device_profile.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


# Descriptor completo (manual)
serialized_pb = b'''
  syntax = "proto3";
  package device_profile;

  message GetDeviceProfileRequest {
    string id = 1;
  }

  message DeviceProfile {
    string id = 1;
    string name = 2;
    string region = 3;
  }

  message ListDeviceProfilesRequest {
    uint32 limit = 1;
    uint32 offset = 2;
    string search = 3;
    string tenant_id = 4;
  }

  message ListDeviceProfilesResponse {
    uint32 total_count = 1;
    repeated DeviceProfile result = 2;
  }
'''
DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(serialized_pb)

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'device_profile.device_profile_pb2', _globals)
# @@protoc_insertion_point(module_scope)
