# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: device_profile/device_profile.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import message
from google.protobuf import descriptor_pb2
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'device_profile/device_profile.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n#device_profile/device_profile.proto\x12\x0e\x64\x65vice_profile\"%\n\x17GetDeviceProfileRequest\x12\n\n\x02id\x18\x01 \x01(\tb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'device_profile.device_profile_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_GETDEVICEPROFILEREQUEST']._serialized_start=55
  _globals['_GETDEVICEPROFILEREQUEST']._serialized_end=92
# @@protoc_insertion_point(module_scope)


class DeviceProfile(message.Message):
    __slots__ = ()
    
    DESCRIPTOR = descriptor_pb2.DescriptorProto(
        name='DeviceProfile',
        field=[
            descriptor_pb2.FieldDescriptorProto(
                name='id',
                number=1,
                label=descriptor_pb2.FieldDescriptorProto.LABEL_OPTIONAL,
                type=descriptor_pb2.FieldDescriptorProto.TYPE_STRING,
            ),
            descriptor_pb2.FieldDescriptorProto(
                name='name',
                number=2,
                label=descriptor_pb2.FieldDescriptorProto.LABEL_OPTIONAL,
                type=descriptor_pb2.FieldDescriptorProto.TYPE_STRING,
            ),
            descriptor_pb2.FieldDescriptorProto(
                name='region',
                number=3,
                label=descriptor_pb2.FieldDescriptorProto.LABEL_OPTIONAL,
                type=descriptor_pb2.FieldDescriptorProto.TYPE_STRING,
            ),
        ]
    )

