# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: device/device.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'device/device.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from chirpstack_proto.api.common import common_pb2 as common_dot_common__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x13\x64\x65vice/device.proto\x12\x03\x61pi\x1a\x13\x63ommon/common.proto\"#\n\x10GetDeviceRequest\x12\x0f\n\x07\x64\x65v_eui\x18\x01 \x01(\t2<\n\rDeviceService\x12+\n\x03Get\x12\x15.api.GetDeviceRequest\x1a\r.api.KeyValueb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'device.device_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_GETDEVICEREQUEST']._serialized_start=49
  _globals['_GETDEVICEREQUEST']._serialized_end=84
  _globals['_DEVICESERVICE']._serialized_start=86
  _globals['_DEVICESERVICE']._serialized_end=146
# @@protoc_insertion_point(module_scope)
