# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from chirpstack_proto.api.device_profile import device_profile_pb2 as device__profile_dot_device__profile__pb2

GRPC_GENERATED_VERSION = '1.74.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in device_profile/device_profile_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class DeviceProfileServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Get = channel.unary_unary(
                '/api.DeviceProfileService/Get',
                request_serializer=device__profile_dot_device__profile__pb2.GetDeviceProfileRequest.SerializeToString,
                response_deserializer=device__profile_dot_device__profile__pb2.DeviceProfile.FromString,
                _registered_method=True)
        self.List = channel.unary_unary(
                '/api.DeviceProfileService/List',
                request_serializer=device__profile_dot_device__profile__pb2.ListDeviceProfilesRequest.SerializeToString,
                response_deserializer=device__profile_dot_device__profile__pb2.ListDeviceProfilesResponse.FromString,
                _registered_method=True)


class DeviceProfileServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def Get(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def List(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_DeviceProfileServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Get': grpc.unary_unary_rpc_method_handler(
                    servicer.Get,
                    request_deserializer=device__profile_dot_device__profile__pb2.GetDeviceProfileRequest.FromString,
                    response_serializer=device__profile_dot_device__profile__pb2.DeviceProfile.SerializeToString,
            ),
            'List': grpc.unary_unary_rpc_method_handler(
                    servicer.List,
                    request_deserializer=device__profile_dot_device__profile__pb2.ListDeviceProfilesRequest.FromString,
                    response_serializer=device__profile_dot_device__profile__pb2.ListDeviceProfilesResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'api.DeviceProfileService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('api.DeviceProfileService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class DeviceProfileService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def Get(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/api.DeviceProfileService/Get',
            device__profile_dot_device__profile__pb2.GetDeviceProfileRequest.SerializeToString,
            device__profile_dot_device__profile__pb2.DeviceProfile.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def List(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/api.DeviceProfileService/List',
            device__profile_dot_device__profile__pb2.ListDeviceProfilesRequest.SerializeToString,
            device__profile_dot_device__profile__pb2.ListDeviceProfilesResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
